description: HOT template for CEE
heat_template_version: 2014-10-16
parameters:
  bootable_image:
    default: Dummy_Image
    description: Upload Dummy_Image
    label: Dummy_Image
    type: string
  flavor1:
    default: CM-Auto_test_flavour
    label: flavor to use for the instance
    type: string
  public_net:
    default: 875be83a-1b5f-4d5c-b21a-4590635f472d
    description: this is the management network
    label: public network
    type: string
  public_net_IP:
    default: 131.160.190.61
    label: IP for public network
    type: string
resources:
  VM-1:
    properties:
      flavor:
        get_param: flavor1
      image:
        get_param: bootable_image
      name: Dummy_Image
      networks:
      - port:
          get_resource: VM-1_port1
    type: OS::Nova::Server
  VM-1_port1:
    properties:
      fixed_ips:
      - ip_address:
          get_param: public_net_IP
      name: Port1
      network:
        get_param: public_net
    type: OS::Neutron::Port
