heat_template_version: 2013-05-23

description: >
  HOT template to deploy VNFLAF Stack in Atlas CEE Environment. i.e. with 2 VMs one hosting the services and another hosting the database.

parameter_groups:
- description: VM Images and Flavors
  parameters:
  - servicesImage
  - services_flavor
  - dbImage
  - db_flavor
  label: Compute
- description: Network details
  parameters:
  - ip_version
  - external_net_id
  - external_subnet_gateway
  - external_subnet_cidr
  - external_ip_for_services_vm
  - external_ipv4_for_db_vm
  - external_ipv6_for_db_vm
  - internal_ipv4_for_db_vm
  - internal_net_id
  label: Network
- description: NFVO/VIM details
  parameters:
  - cloudManagerType
  label: CloudManager
- description: ENM/OSS-RC details
  parameters:
  - ossType
  - ossMasterHostName
  - ossMasterHostIP
  - ossNotificationServiceHost
  - ossNotificationServiceIP
  - ossUserName
  label: OSS

parameters:
  ossMasterHostIP:
    default: 
    type: string
    description: OSSRC Live Admin server host IP for VNF(s) to be connected. Example
      - 131.160.162.195
  external_subnet_cidr:
    default: 
    type: string
    description: IP address range of IPv4/Ipv6 subnet of external network. Example
      - 10.148.14.0/25 or 2001:1b70:6207:2b::/64
  ossType:
    default: OSSRC
    type: string
    description: Type of OSS. Example - OSSRC,ENM etc.
  ossNotificationServiceHost:
    default: notificationservice
    type: string
    description: Host name of the Host where notification service of OSS is running.
      Refer parameter table in Installation Guide to find the description. Example
      - notificationservice
  ossMasterHostName:
    default: 
    type: string
    description: OSSRC Live Admin server hostname for VNF(s) to be connected. Example
      - osshostname.athtem.eei.ericsson.se
  ossUserName:
    default: nmsadm
    type: string
    description: Authorized user of OSSRC Server for VNF handling. Example - nmsadm
  external_subnet_gateway:
    default: 
    type: string
    description: External network gateway address of IPv4/Ipv6 subnet. Example - 10.148.14.1
      or 2001:1b70:6207:2b:0:3522:0:1
  external_ip_for_services_vm:
    default: 
    type: string
    description: IPv4/IPv6 address for the vnflcm VM. Example - 131.160.162.10 or  2001:1b70:6207:2b:0:309:0:999b
  ossNotificationServiceIP:
    type: string
    description: IP address of the Host where notification service of OSS is running.
      Refer parameter table in Installation Guide to find the description. Example
      - 10.140.23.40
  services_flavor:
    default: m1.medium
    type: string
    description: Flavor to use for vnflaf-services VM. 2vcpu_6144MBmem_20GBdisk
    constraints:
    - allowed_values:
      - m1.medium
  servicesImage:
    default: ERICvnflafdevimage_CXP9032638-3.6.17.qcow2
    type: string
    description: Name of vnflafdevimage VM image ERICvnflafdevimage_CXP9032638-3.4.19.qcow2
      uploaded to CEE Atlas.
  cloudManagerType:
    default: CEE
    type: string
    description: Cloud Manager type. ECM/CEE/Openstack -  This input will be used
      by VNF-LAF to prepare the environment to execute workflows. Example - CEE
  external_net_id:
    default: 
    type: string
    description: Id of Pre created IPv4/Ipv6 external network. ID can be obtained
      from Atlas CEE/Openstack dashborad. Example - 68559cad-f3bb-4dbe-8483-d15757763f80
  ip_version:
    default: 4
    type: string
    description: IP version to be configured. IPv4 or IPv6
    constraints:
    - allowed_values:
      - 4
      - 6
  dbImage:
    default: ERICrhelpostgresimage_CXP9032491-3.4.4
    description: Name of vnflaf-db VM image uploaded ERICrhelpostgresimage_CXP9032491-3.1.14
      to Openstack dashboard.
    type: string
  db_flavor:
    constraints:
    - allowed_values:
      - vnflaf-db
      - m1.medium
      - m1.small
    default: m1.medium
    description: Flavor for vnflaf-db VM. 2vcpu_4096MBmem_40GBdisk
    type: string
  external_ipv4_for_db_vm:
    default: 131.160.162.48
    description: IPv4 address for the vnflaf-db VM. Example - 131.160.162.10
    type: string
  external_ipv6_for_db_vm:
    default: None
    description: IPv6 address for the vnflaf-db VM. Example -      2001:1b70:6207:25:0:309:0:999a
    type: string
  internal_ipv4_for_db_vm:
    default: 172.16.100.3
    description: Internal IPv4 address for the vnflaf-db VM. Example - 172.16.100.2
    type: string
  internal_ipv6_for_db_vm:
    default: None
    description: Internal IPv6 address for the vnflaf-db VM. Example - fd5b:1fd5:8295:5339::5
    type: string
  internal_net_id:
    default: bc464c56-0cb3-4ad1-b818-c264efb1a93c
    description: Id of Pre created IPv4/dualstack internal network. ID can be obtained
      from Atlas/Openstack dashborad. Example - 2958594d-c56f-4508-bc9b-23de74527942
    type: string
outputs:
  vnflaf_services_external_ip:
    description: IP address of VNFLAF-Services in external network
    value:
      get_param: external_ip_for_services_vm
  vnflaf_db_external_ipv4:
    description: External IP address of VNFLAF-Services
    value:
      get_param: external_ipv4_for_db_vm
  vnflaf_db_external_ipv6:
    description: External IP address of VNFLAF-Services
    value:
      get_param: external_ipv6_for_db_vm
  vnflaf_db_internal_ip:
    description: Internal IP address of VNFLAF-DB
    value:
      get_param: internal_ipv4_for_db_vm
resources:
  server_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
      - config:
          get_resource: services-cloud-init
  vnflaf-services:
    type: OS::Nova::Server
    properties:
      user_data_format: RAW
      name: VNFLAF-Services
      image:
        get_param: servicesImage
      user_data:
        get_resource: server_init
      flavor:
        get_param: services_flavor
      metadata:
        ha-policy: ha-offline
      networks:
      - port:
          get_resource: vnflaf_services_external_port
      config_drive: true
  services-cloud-init:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        bootcmd:
        - echo "Boot Completed"
        ssh_pwauth: true
        disable_root: false
        hostname: enm-lvs
        chpasswd:
          list: |
            cloud-user:cloudUser
            expire: false
        write_files:
        - owner: root:root
          path: "/ericsson/vnflcm/data/host.properties"
          content:
            str_replace:
              params:
                __EXTERNAL_SUBNET_CIDR__:
                  get_param: external_subnet_cidr
                __OSS_HOST_NAME__:
                  get_param: ossMasterHostName
                __IP_VERSION__:
                  get_param: ip_version
                __OSS_NOTIFICATION_SERVICE_IP__:
                  get_param: ossNotificationServiceIP
                __CLOUD_MGR_TYPE__:
                  get_param: cloudManagerType
                __OSS_NOTIFICATION_SERVICE_HOST_NAME__:
                  get_param: ossNotificationServiceHost
                __OSS_USER_NAME__:
                  get_param: ossUserName
                __OSSRC_MASTER_HOST_IP__:
                  get_param: ossMasterHostIP
                __VNFLAF_SERVICES_EXTERNAL_IP__:
                  get_param: external_ip_for_services_vm
                __OSS_TYPE__:
                  get_param: ossType
                __EXTERNAL_SUBNET_GATEWAY__:
                  get_param: external_subnet_gateway
              template: "\n#Plan to be executed for configuring the host\nconfiguration_plan=runtime,network,db,services,storage,security,params\n\n#
                Ethernet interface configuration\nip_version=__IP_VERSION__\nvlans=external\nexternal_eth_interface=eth0\nexternal_subnet_cidr=__EXTERNAL_SUBNET_CIDR__\nexternal_ip_address=__VNFLAF_SERVICES_EXTERNAL_IP__\nexternal_gateway=__EXTERNAL_SUBNET_GATEWAY__\n\n#Storage\nstorageType=local\n#
                Only for NFS\n#nfsServerIp=__NFS_SERVER_IP__\n#sharedFilesystemPath=__SHARED_FS_PATH__\n\n#
                /etc/hosts entries\nhost_entries=loopback_ipv__IP_VERSION__,this_host,oss_host,oss_notification_service_host\nloopback_ipv4=\"127.0.0.1
                \  localhost httpd-1-instance\"\nloopback_ipv6=\"::1   localhost httpd-1-instance\"\nthis_host=\"__VNFLAF_SERVICES_EXTERNAL_IP__
                \ vnflaf-services  vnflaf-db  postgresql01\"\noss_host=\"__OSSRC_MASTER_HOST_IP__
                \ __OSS_HOST_NAME__  masterservice  mashost\"\noss_notification_service_host=\"__OSS_NOTIFICATION_SERVICE_IP__
                \  __OSS_NOTIFICATION_SERVICE_HOST_NAME__\"\n\n# Hostname\nthis_hostname=vnflaf-services\n\n#Users\nusers=cloud-user\n\n#Service
                Groups\nservice_groups_on_host=vnflcm-services,vnflcm-ui,vnflcm-db\n\n#Services\nservices=sshd,httpd,modeldeployservice,jboss,network,ntpd,nfs\nntpServer=__OSSRC_MASTER_HOST_IP__\n\n#security
                plan\nsecurity_plan=certificates\n\n#Versions  \nvnflcm_media_version=1.1.61\nvnflcm_services_image_version=3.0.69\n#vnflcm_db_image_version=2.0.22\n\nwfs_db_schema_version=1.0.0\nsfwk_db_schema_version=1.0.0\nvnflcm_db_schema_version=1.0.0\n\n#
                Configuration parameters for VNFLCM-SDK\n#Cloud Manager\ncloudManagerType=__CLOUD_MGR_TYPE__\n\n#
                Configuration parameters for Element manager\nossType=__OSS_TYPE__\nossMasterHostName=__OSS_HOST_NAME__\nossNotificationServiceHost=__OSS_NOTIFICATION_SERVICE_HOST_NAME__\nossMasterHostIP=__OSSRC_MASTER_HOST_IP__\nossUserName=__OSS_USER_NAME__\n"
          permissions: '0777'
        runcmd:
        - "/opt/ericsson/ERICvnflafinst_CXP9032542/bin/configure_host.sh"
  vnflaf-db:
    properties:
      config_drive: true
      flavor:
        get_param: db_flavor
      image:
        get_param: dbImage
      metadata:
        ha-policy: ha-offline
      name: ''
      networks:
      - port:
          get_resource: vnflaf_db_internal_port
      - port:
          get_resource: vnflaf_db_external_port
      user_data_format: RAW
    type: OS::Nova::Server
  vnflaf_services_external_port:
    type: OS::Neutron::Port
    properties:
      network_id:
        get_param: external_net_id
      fixed_ips:
      - ip_address:
          get_param: external_ip_for_services_vm
  vnflaf_db_internal_port:
    properties:
      allowed_address_pairs:
      - ip_address: 0.0.0.0/0
      - ip_address: "::/0"
      fixed_ips:
      - ip_address:
          get_param: internal_ipv4_for_db_vm
      network_id:
        get_param: internal_net_id
    type: OS::Neutron::Port
  vnflaf_db_external_port:
    properties:
      allowed_address_pairs:
      - ip_address: 0.0.0.0/0
      - ip_address: "::/0"
      fixed_ips:
      - ip_address:
          get_param: external_ipv4_for_db_vm
      network_id:
        get_param: external_net_id
    type: OS::Neutron::Port
